### ISSUE TITLE
Cannot login in Staging App

### ISSUE THREAD

**Issue by unc0ded** [paytm/Paytm_Payments_Android_Sample_Apps#7]
Hi, I'm trying to login in the staging app with the credentials 7777777777 and static otp 888888 as given in developer docs. However the app asks for Paytm password instead of OTP, and reset password is also not an option as it gives an error "Client permission not found". How to go about this then? Is there a change the docs have not yet mentioned?

**Comment by soumyavats** [comment]
Please use password "Paytm12345"

**Comment by unc0ded** [comment]
Thanks

**Comment by mehulagg** [comment]
Please update this on developer docs.

**Comment by mallikarjun-patel** [comment]
Only otp option is coming
